implemented a Drawer
JohannesF99/mobile_application_3 pull request #29
Opened 2023-02-21 09:42 UTC by Smurado

- added one element: language button

2023-02-21 09:43 UTC, Smurado commented
im oce again, asking for your review

2023-02-27 09:19 UTC, JohannesF99 commented on lib/l10n/l10n.dart
> +class L10n{
Wäre cool, wenn der Klassenname auch mit dem Dateinamen übereinstimmt.
Könntest du da quasi die Datei noch in _L10n.dart_ umbenennen?

2023-03-22 09:52 UTC, JohannesF99 requested changes
Paar kleine Änderung, aber nur hauptsächlich Formatierungen, sonst passt alles 👍🏽

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/HomeScreen.dart
Hier mal bitte noch die 6 Warnings entfernen.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/LanguageSelect.dart
Hier bitte auch noch die Warnings entfernen.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/NewReminderScreen.dart
Hier auch Warnings.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/ReminderScreen.dart
Hier auch Warnings.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/WelcomeScreen.dart
Hier auch Warnings.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/util/CountDownUtil.dart
Warnings.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/widget/AddNotesButton.dart
Warnings.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/widget/NoteList.dart
Warnings.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/widget/NotificationList.dart
Warnings.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/LanguageSelect.dart
> +                          //Navigator.pop(context, 'de');
Kommentar kann glaube ich noch weg, oder?

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/LanguageSelect.dart
> +                  child: ListView(
Die ListView könnte man auch mit einem `ListView.Builder()` dynamisch generieren, dann würde sie automatisch für noch kommende Sprachen wachsen, anstatt sie hart rein zu coden. Muss aber nicht.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/NewReminderScreen.dart
> +
Die extra Leerzeile kann glaube weg. :D

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/NewReminderScreen.dart
> +    //final Locale appLocale = Localizations.localeOf(context);
Kommentar kann glaube auch weg, oder?

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/NewReminderScreen.dart
> +        //crossAxisAlignment: CrossAxisAlignment.start,
Kommentar kann auch weg.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/NewReminderScreen.dart
> +
Leerzeile kann auch weg

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/NewReminderScreen.dart
> +                  child: _date != null ? Text(_date!.toReadable(time: true, am: AppLocalizations.of(context)!.on, um: AppLocalizations.of(context)!.at, stunde: AppLocalizations.of(context)!.hour),
Das eventuell noch mit Zeilenumbrüchen etwas lesbarer machen. Muss aber nicht.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/NewReminderScreen.dart
> +
Leerzeile kann weg.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/NewReminderScreen.dart
> +            //margin: const EdgeInsets.all(10),
Kommentar kann auch weg.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/screen/ReminderScreen.dart
> +
Leerzeile kann weg.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/util/DateTimeUtil.dart
> +      return !time ? output : "$output, $um ${hour.getNumberAddZero()}:"
Das Return ist eingerückt und die Leerzeile kann glaube auch weg.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/widget/AddNotesButton.dart
> +                      //margin: const EdgeInsets.all(10),
Kommentar kann weg?

2023-03-22 09:52 UTC, JohannesF99 commented on lib/widget/AddNotesButton.dart
> +
Leerzeile.

2023-03-22 09:52 UTC, JohannesF99 commented on lib/widget/NoteList.dart
> +            //height: MediaQuery.of(context).size.height-435,
Kommentar kann weg, oder?

2023-03-22 09:52 UTC, JohannesF99 commented on lib/widget/ReminderTile.dart
> +
Leerzeile kann weg

2023-03-22 11:38 UTC, JohannesF99 requested changes
Warnings noch weg, dann können wir mergen.

2023-03-22 11:38 UTC, JohannesF99 commented on lib/screen/HomeScreen.dart
Da sind immer noch Warnings

2023-03-22 11:38 UTC, JohannesF99 commented on lib/screen/NewReminderScreen.dart
Hier auch.

2023-03-22 11:38 UTC, JohannesF99 commented on lib/screen/ReminderScreen.dart
Hier auch.

2023-03-22 11:38 UTC, JohannesF99 commented on lib/widget/AddNotesButton.dart
Hier auch.

2023-03-22 11:38 UTC, JohannesF99 commented on lib/widget/NoteList.dart
Hier auch.

2023-03-22 11:45 UTC, JohannesF99 approved these changes

2023-03-22 11:46 UTC, JohannesF99 submitted a review, later dismissed

2023-03-22 11:53 UTC, closed without merging